git_ssh_key: ((git_ssh_key.private_key))
cf_endpoint: https://api.sys.nonprod.dryice01.in.hclcnlabs.com
cf_user: ((cf_user))
cf_password: ((cf_password))
cf_org: DryIce
cf_space: Dev
app_bucket: spring-music
app_storage_account_name: indryice01devs
app_storage_account_key: ((app_storage_account_key))


