platform: linux
image_resource: 
  type: docker-image
  source:
    repository: pcfnorm/rootfs
    tag: latest

inputs:
  - name: pipelines-repo

run: 
  path: pipelines-repo/tasks/hello-world/task.sh

