platform: linux
image_resource: 
  type: docker-image
  source:
    repository: pcfnorm/rootfs
    tag: latest

inputs:
  - name: app-pipeline
  - name: build-store

run: 
  path: app-pipeline/tasks/test-app/task.sh

