platform: linux
image_resource: 
  type: docker-image
  source:
    repository: gradle
    tag: jdk8

inputs:
  - name: app-pipeline
  - name: spring-music

outputs:
  - name: spring-music-build

run: 
  path: app-pipeline/tasks/build-app/task.sh
  user: root
