platform: linux
image_resource: 
  type: docker-image
  source:
    repository: pcfnorm/rootfs
    tag: latest

inputs:
  - name: app-pipeline

run: 
  path: app-pipeline/tasks/test-deploy/task.sh

